version: "3.8"
services:
  angular:
    build: angular
    ports:
      - "4200:4200"

  express:
    build: express
    ports:
      - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db

# @TODO nginx setup to proxy all this apps 
